import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins, Roboto } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";



export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "VitaLink - Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="w-full ">
        {children}
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
